//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonarSangre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int DonorId { get; set; }
        public string Name_Don { get; set; }
        public string Last_Name_Don { get; set; }
        public int CityId { get; set; }
        public int ZipCode { get; set; }
        public Nullable<System.DateTime> Last_Date_Blood_Extract { get; set; }
        public int GroupId { get; set; }
        public int FactorId { get; set; }
    
        public virtual Blood_Factor Blood_Factor { get; set; }
        public virtual Blood_Group Blood_Group { get; set; }
        public virtual City City { get; set; }
    }
}
